language: go

go:
  - 1.4

install:
  - go get code.google.com/p/go-uuid/uuid
  - go get github.com/gogo/protobuf/proto
  - go get github.com/golang/glog
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/mock
  - go get github.com/samuel/go-zookeeper/zk
  - go get github.com/gorilla/mux
  - go get github.com/fsouza/go-dockerclient
  - go get github.com/davecgh/go-spew/spew
  - go get github.com/ghodss/yaml
  - go get github.com/socketplane/libovsdb

script:
  - go test -v ./...