language: go

go:
  - 1.4

install:
  - go get code.google.com/p/go-uuid/uuid
  - go get github.com/gogo/protobuf/proto
  - go get github.com/golang/glog
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/mock
  - go get github.com/samuel/go-zookeeper/zk
  - go get github.com/gorilla/mux

script:
  - go test -v ./...